// SCM variant - public-data supply-chain monitoring demo
// NOTE: Runtime wiring lives in src/config/panels.ts. This file is the
// structured reference alongside energy.ts / commodity.ts / finance.ts.
import type { PanelConfig, MapLayers } from '@/types';
import type { VariantConfig } from './base';

export * from './base';

export const DEFAULT_PANELS: Record<string, PanelConfig> = {
  map: { name: 'Public SCM Demo Map', enabled: true, priority: 1 },
  'energy-risk-overview': { name: 'Public Energy Supply Risk Overview', enabled: true, priority: 1 },
  'chokepoint-strip': { name: 'Chokepoint Status', enabled: true, priority: 1 },
  'supply-chain': { name: 'Supply Chain & Chokepoints', enabled: true, priority: 1 },
  'trade-policy': { name: 'Trade Policy & Controls', enabled: true, priority: 1 },
  'sanctions-pressure': { name: 'Sanctions Pressure', enabled: true, priority: 1 },
  'pipeline-status': { name: 'Pipeline Status', enabled: true, priority: 1 },
  'storage-facility-map': { name: 'Storage Facilities', enabled: true, priority: 1 },
  'fuel-shortages': { name: 'Fuel Shortages', enabled: true, priority: 1 },
  'energy-disruptions': { name: 'Energy Disruptions', enabled: true, priority: 1 },
  'live-news': { name: 'Supply Chain & Energy Headlines', enabled: true, priority: 1 },
  'energy-complex': { name: 'Energy Complex', enabled: true, priority: 1 },
  'oil-inventories': { name: 'Oil & Gas Inventories', enabled: true, priority: 1 },
  'hormuz-tracker': { name: 'Strait of Hormuz Tracker', enabled: true, priority: 1 },
  commodities: { name: 'Energy & Materials Benchmarks', enabled: true, priority: 1 },
  'fuel-prices': { name: 'Fuel Prices', enabled: true, priority: 2 },
  'macro-signals': { name: 'Macro Signals', enabled: true, priority: 2 },
  monitors: { name: 'My Monitors', enabled: true, priority: 3 },
};

export const DEFAULT_MAP_LAYERS: MapLayers = {
  pipelines: true,
  storageFacilities: true,
  fuelShortages: true,
  waterways: true,
  tradeRoutes: true,
  ais: true,
  commodityPorts: true,
  commodityHubs: true,
  minerals: true,
  sanctions: true,
  weather: true,
  natural: true,
  fires: true,
  outages: true,
  liveTankers: true,
  gpsJamming: false,
  satellites: false,
  iranAttacks: false,
  conflicts: false,
  bases: false,
  cables: false,
  hotspots: false,
  nuclear: false,
  irradiators: false,
  economic: false,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  spaceports: false,
  ucdpEvents: false,
  displacement: false,
  climate: false,
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  gulfInvestments: false,
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  ciiChoropleth: false,
  resilienceScore: false,
  dayNight: false,
  miningSites: false,
  processingPlants: false,
  webcams: false,
  diseaseOutbreaks: false,
};

export const MOBILE_DEFAULT_MAP_LAYERS: MapLayers = {
  pipelines: true,
  storageFacilities: true,
  fuelShortages: true,
  waterways: true,
  commodityPorts: true,
  sanctions: true,
  outages: true,
  natural: true,
  tradeRoutes: false,
  ais: false,
  commodityHubs: false,
  minerals: false,
  weather: false,
  fires: false,
  liveTankers: false,
  gpsJamming: false,
  satellites: false,
  iranAttacks: false,
  conflicts: false,
  bases: false,
  cables: false,
  hotspots: false,
  nuclear: false,
  irradiators: false,
  economic: false,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  spaceports: false,
  ucdpEvents: false,
  displacement: false,
  climate: false,
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  gulfInvestments: false,
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  ciiChoropleth: false,
  resilienceScore: false,
  dayNight: false,
  miningSites: false,
  processingPlants: false,
  webcams: false,
  diseaseOutbreaks: false,
};

export const VARIANT_CONFIG: VariantConfig = {
  name: 'scm',
  description: 'Public-data SCM monitoring demo for energy routes, storage, shortages, sanctions, and trade controls',
  panels: DEFAULT_PANELS,
  mapLayers: DEFAULT_MAP_LAYERS,
  mobileMapLayers: MOBILE_DEFAULT_MAP_LAYERS,
};
