import type { ScmMaterialMapping, ScmRoutePreset } from '@/types/scm-route-materials';

export const SCM_MATERIAL_MAPPINGS: readonly ScmMaterialMapping[] = [
  {
    materialId: 'crude-refined-fuels',
    label: 'Crude and refined fuels',
    hs2: '27',
    productLabel: 'Mineral fuels and energy',
    confidence: 'high',
    sourceNote: {
      source: 'Public HS chapter mapping',
      note: 'HS chapter 27 directly covers mineral fuels, oils, and related energy products.',
    },
    fallback: {
      reason: 'High-confidence public HS mapping exists.',
      copy: 'Public HS chapter 27 supports fuel and feedstock route context for this demo corridor.',
    },
    signalCategories: ['route_chokepoint', 'fuel_shortage', 'energy_disruption', 'market_context'],
  },
  {
    materialId: 'critical-battery-inputs',
    label: 'Battery and critical-mineral inputs',
    hs2: '26',
    productLabel: 'Ores, slag and ash',
    confidence: 'medium',
    sourceNote: {
      source: 'Public HS chapter and critical-minerals context',
      note: 'HS chapter 26 is a broad proxy for ores and concentrates; processed battery inputs may map elsewhere.',
    },
    fallback: {
      reason: 'Public product mapping is broad.',
      copy: 'Public sources support a broad ores/minerals proxy here, not a precise battery-material flow claim.',
    },
    signalCategories: ['route_chokepoint', 'critical_minerals', 'market_context'],
  },
  {
    materialId: 'industrial-equipment',
    label: 'Industrial equipment and spares',
    hs2: '84',
    productLabel: 'Machinery and mechanical appliances',
    confidence: 'medium',
    sourceNote: {
      source: 'Public HS chapter mapping',
      note: 'HS chapter 84 is a broad equipment category suitable for demo supply-chain context.',
    },
    fallback: {
      reason: 'Equipment category is broad.',
      copy: 'Public HS chapter 84 supports equipment context, but does not identify a specific operational item.',
    },
    signalCategories: ['route_chokepoint', 'pipeline_storage'],
  },
  {
    materialId: 'process-chemicals',
    label: 'Process chemicals',
    hs2: '38',
    productLabel: 'Chemical products',
    confidence: 'low',
    sourceNote: {
      source: 'Public HS chapter mapping',
      note: 'HS chapter 38 is a broad chemical-products category and should stay fallback-framed.',
    },
    fallback: {
      reason: 'Public sources do not support precise material-to-product mapping.',
      copy: 'Public sources do not support a precise product mapping for this material in the demo.',
    },
    signalCategories: ['route_chokepoint', 'energy_disruption'],
  },
  {
    materialId: 'unmapped-energy-material',
    label: 'Unmapped energy material',
    hs2: null,
    productLabel: null,
    confidence: 'unavailable',
    sourceNote: {
      source: 'Public mapping unavailable',
      note: 'No defensible public HS chapter mapping is configured for this demo material.',
    },
    fallback: {
      reason: 'No public mapping configured.',
      copy: 'No defensible public HS/product mapping is available for this material in the demo.',
    },
    signalCategories: ['market_context'],
  },
];

export const SCM_ROUTE_PRESETS: readonly ScmRoutePreset[] = [
  {
    id: 'demo-gulf-energy-feedstock',
    label: 'Demo Gulf energy feedstock corridor',
    dataPosture: 'public_demo_corridor',
    originIso2: 'SA',
    originLabel: 'Saudi Arabia',
    destinationIso2: 'IN',
    destinationLabel: 'India',
    hs2: '27',
    productLabel: 'Mineral fuels and energy',
    cargoType: 'tanker',
    materialIds: ['crude-refined-fuels'],
    routeIds: ['gulf-asia-oil'],
    chokepointIds: ['hormuz_strait', 'malacca_strait'],
    signalCategories: ['route_chokepoint', 'fuel_shortage', 'energy_disruption', 'market_context'],
    rationale: 'Public geography and HS chapter 27 provide a useful demo corridor for energy feedstock exposure.',
    sourceNote: {
      source: 'WorldMonitor public route/chokepoint model',
      note: 'Demo corridor based on public chokepoint geography and energy product categories.',
    },
    freshnessLabel: 'Uses latest available public route and chokepoint signals.',
    confidence: 'high',
  },
  {
    id: 'demo-east-asia-critical-inputs',
    label: 'Demo East Asia critical-inputs corridor',
    dataPosture: 'public_demo_corridor',
    originIso2: 'CN',
    originLabel: 'China',
    destinationIso2: 'US',
    destinationLabel: 'United States',
    hs2: '26',
    productLabel: 'Ores, slag and ash',
    cargoType: 'bulk',
    materialIds: ['critical-battery-inputs'],
    routeIds: ['china-us-west', 'china-us-east-panama'],
    chokepointIds: ['taiwan_strait', 'panama'],
    signalCategories: ['route_chokepoint', 'critical_minerals', 'market_context'],
    rationale: 'Public trade geography and broad HS chapter 26 support critical-mineral route context without private demand assumptions.',
    sourceNote: {
      source: 'Public HS chapter and WorldMonitor route context',
      note: 'Demo corridor uses public country, route, and material-category context.',
    },
    freshnessLabel: 'Uses public route and critical-minerals context where available.',
    confidence: 'medium',
  },
  {
    id: 'demo-north-american-equipment',
    label: 'Demo North American equipment corridor',
    dataPosture: 'public_demo_corridor',
    originIso2: 'CA',
    originLabel: 'Canada',
    destinationIso2: 'US',
    destinationLabel: 'United States',
    hs2: '84',
    productLabel: 'Machinery and mechanical appliances',
    cargoType: 'container',
    materialIds: ['industrial-equipment'],
    routeIds: ['us-europe-lng'],
    chokepointIds: [],
    signalCategories: ['pipeline_storage', 'route_chokepoint'],
    rationale: 'A lower-chokepoint regional demo corridor helps compare equipment exposure against maritime chokepoint routes.',
    sourceNote: {
      source: 'Public country/product exposure context',
      note: 'Demo corridor uses public country and product categories only.',
    },
    freshnessLabel: 'Regional corridor context; route data may be partial.',
    confidence: 'medium',
  },
  {
    id: 'demo-process-chemicals',
    label: 'Demo process-chemicals corridor',
    dataPosture: 'public_demo_corridor',
    originIso2: 'DE',
    originLabel: 'Germany',
    destinationIso2: 'US',
    destinationLabel: 'United States',
    hs2: '38',
    productLabel: 'Chemical products',
    cargoType: 'container',
    materialIds: ['process-chemicals', 'unmapped-energy-material'],
    routeIds: ['china-us-east-suez'],
    chokepointIds: ['suez'],
    signalCategories: ['route_chokepoint', 'energy_disruption', 'market_context'],
    rationale: 'Broad public chemical-products context demonstrates low-confidence material fallback behavior.',
    sourceNote: {
      source: 'Public HS chapter mapping',
      note: 'Demo corridor intentionally keeps chemical material context broad.',
    },
    freshnessLabel: 'Uses public route context; material mapping confidence is limited.',
    confidence: 'low',
  },
];

export function findScmMaterialMapping(materialId: string): ScmMaterialMapping | undefined {
  return SCM_MATERIAL_MAPPINGS.find(mapping => mapping.materialId === materialId);
}
