import type { SupplierRiskArchetype } from '@/types/supplier-risk';

export const PUBLIC_SUPPLIER_RISK_ARCHETYPES: SupplierRiskArchetype[] = [
  {
    id: 'gulf-feedstock-archetype',
    label: 'Gulf feedstock archetype',
    dataPosture: 'synthetic_archetype',
    exporterIso2: 'SA',
    exporterLabel: 'Saudi Arabia',
    importerIso2: 'IN',
    importerLabel: 'India',
    hs2: '27',
    productLabel: 'Energy feedstocks',
    materials: ['crude oil', 'refined fuels'],
    publicSources: [
      'WorldMonitor public route/chokepoint model',
      'Public energy product category mapping',
    ],
    notes: 'Synthetic archetype for public Gulf-to-Asia energy route exposure.',
  },
  {
    id: 'north-american-equipment-archetype',
    label: 'North American equipment archetype',
    dataPosture: 'synthetic_archetype',
    exporterIso2: 'CA',
    exporterLabel: 'Canada',
    importerIso2: 'US',
    importerLabel: 'United States',
    hs2: '84',
    productLabel: 'Industrial machinery',
    materials: ['steel', 'industrial equipment'],
    publicSources: [
      'WorldMonitor public route/chokepoint model',
      'Public country/product exposure archetype',
    ],
    notes: 'Synthetic archetype for lower-chokepoint North American equipment exposure.',
  },
  {
    id: 'east-asia-battery-materials-archetype',
    label: 'East Asia battery materials archetype',
    dataPosture: 'synthetic_archetype',
    exporterIso2: 'CN',
    exporterLabel: 'China',
    importerIso2: 'US',
    importerLabel: 'United States',
    hs2: '85',
    productLabel: 'Electrical and battery inputs',
    materials: ['lithium', 'graphite', 'rare earths'],
    publicSources: [
      'Public energy materials relevance signal',
      'WorldMonitor public route/chokepoint model',
    ],
    notes: 'Synthetic archetype for public materials and route exposure, not a customer supplier file.',
  },
  {
    id: 'low-coverage-archetype',
    label: 'Low coverage public-signal archetype',
    dataPosture: 'public_signal_summary',
    exporterIso2: 'ZZ',
    exporterLabel: 'Unmodeled public exporter',
    importerIso2: 'US',
    importerLabel: 'United States',
    hs2: '99',
    productLabel: 'Unmapped public product signal',
    materials: [],
    publicSources: [
      'Public signal coverage placeholder',
    ],
    notes: 'Public-signal summary used to show low-confidence fallback behavior.',
  },
];
